django:
        build: ./docker/django
        command: ./manage.py runserver 0.0.0.0:8080
        ports:
                - "8080:8080"
        volumes:
                - .:/django
        volumes_from:
                - bowerjs
        links:
                - postgres
bowerjs:
        build: ./docker/bowerjs
        volumes:
                - /django/permit_map/static/permit_map/bower_components
postgres:
        build: ./docker/postgis
        ports:
                - "5432:5432"
        environment:
                POSTGRES_PASSWORD: cfac
                POSTGRES_USER: cfac
